In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn 
import warnings
warnings.filterwarnings("ignore")

In [2]:
data={
    "EmployeeId":[101,102,103,104,105],
    "Salary":[30000,4000,5000,30000,40000],
    "Name":["Sumanth","santhosh","Surendra","Mansa","Bhargavi"]
}
pf=pd.DataFrame(data)
print(pf)

   EmployeeId  Salary      Name
0         101   30000   Sumanth
1         102    4000  santhosh
2         103    5000  Surendra
3         104   30000     Mansa
4         105   40000  Bhargavi

In [4]:
pf["Salary"]

0    30000
1     4000
2     5000
3    30000
4    40000
Name: Salary, dtype: int64

In [11]:
pf.loc[:,["Salary","Name"]]

   Salary      Name
0   30000   Sumanth
1    4000  santhosh
2    5000  Surendra
3   30000     Mansa
4   40000  Bhargavi

In [44]:
# Numpy 
# pip install numpy 
import numpy as np 
arr1=np.array([])
print(arr1) # displaying the empty array
arr2=[100,200,300,400] # craeting the list 
df=np.array(arr2) # coverting the list in to np array 
print(df)# printing the np array 
# we have to check the type of the array 
print(type(df))
# We are checking the dimension of the array 
print(df.ndim) # it has only one dimension 
# printing the size of the array 
print(df.size) # the size of the array id 4
# checking the shape of the array 
print(df.shape) # the shape 4
# concatenating the list 
arr2+[200] # adding the data to existing list 
# checking the datatype 
print(df.dtype) # the datatype is int64
# we have to check the mean of the array 
print(np.mean(df)) # the mean is 250
# reshapping 
print(df.reshape(2,2)) # we reshape to 2 rows to two columns 
# flatten function it use to convert the n dimenssional array in to one dimensional array 
print(df.flatten()) # its converted 
#Arange concept 
print(np.arange(15))
print(np.arange(2,100,10)) # three are same with small difference we know that difference 
print(np.arange(2,50))
# we want to print one d array with zeros 
print(np.zeros(3))
print(np.zeros((1,10)))
# we can ones with n dimenssional 
print(np.ones((2,5,6)))
# lines space 
print(np.linspace(1,15))
print(np.linspace(2,25,10,retstep=True))
# creatig the identity matrix
print(np.eye(2,2))
# boarding casting 
print(df+6)
# copy 
pf=df.copy() # copy function retains the original copy and creates the backup 
print(pf)
# random numbers 
print(np.random.rand(2,2))

[]
[100 200 300 400]
<class 'numpy.ndarray'>
1
4
(4,)
int64
250.0
[[100 200]
 [300 400]]
[100 200 300 400]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2 12 22 32 42 52 62 72 82 92]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]
(array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
       14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ]), np.float64(2.5555555555555554))
[[1. 0.]
 [0. 1.]]
[106 206 306 406]
[100 200 300 400]

array([[0.24346251, 0.43785763],
       [0.40794106, 0.51619252]])

In [54]:
print(np.random.randint(1,2000,10))
print(np.random.randn(2,3,1))
#printing mean median variance std 
print(df)
print(np.mean(df),np.median(df),np.var(df),np.std(df))
# array attridutes 
print(df.max(),df.min(),df.argmax(),df.argmin())

[1898 1735  907  102 1057 1805  409 1901   46 1145]
[[[ 0.58943287]
  [-0.54878279]
  [-1.26268108]]

 [[ 0.52370326]
  [-1.32156129]
  [-0.32807939]]]
[100 200 300 400]
250.0 250.0 12500.0 111.80339887498948
400 100 3 0

In [60]:
# pandas 
import pandas as pd 
data={
    "EmployeeID":[101,102,103,104,105],
    "Emp Name":["Sumanth","Sudheer","Surendra","Nagamani","nagaraju"],
    "Dept":["IT","IT","HR","HR","IT"],
    "Salary":[20000,30000,40000,30000,40000],
    "Exp":[2,3,4,5,6]
}
df=pd.DataFrame(data)
print(df)

   EmployeeID  Emp Name Dept  Salary  Exp
0         101   Sumanth   IT   20000    2
1         102   Sudheer   IT   30000    3
2         103  Surendra   HR   40000    4
3         104  Nagamani   HR   30000    5
4         105  nagaraju   IT   40000    6

In [63]:
df=pd.read_csv(r"D:\Downloads\Data Science Shared-20260811T032730Z-1-001\Data Science Shared\car data.csv")

In [65]:
# understanding your dataset 
df.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

In [66]:
df.tail(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
291,brio,2015,5.40,6.10,31427,Petrol,Dealer,Manual,0
292,jazz,2016,6.40,8.40,12000,Petrol,Dealer,Manual,0
293,city,2010,3.25,9.90,38000,Petrol,Dealer,Manual,0
294,amaze,2014,3.75,6.80,33019,Petrol,Dealer,Manual,0
295,city,2015,8.55,13.09,60076,Diesel,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [67]:
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [69]:
df.shape

(301, 9)

In [70]:
df.size

2709

In [71]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [72]:
df.index

RangeIndex(start=0, stop=301, step=1)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [74]:
df.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Owner              int64
dtype: object

In [76]:
df.nunique()

Car_Name          98
Year              16
Selling_Price    156
Present_Price    147
Kms_Driven       206
Fuel_Type          3
Seller_Type        2
Transmission       2
Owner              3
dtype: int64

In [83]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [85]:
df=pd.DataFrame(df)

In [86]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [90]:
df.loc[:, "Car_Name"]

0         ritz
1          sx4
2         ciaz
3      wagon r
4        swift
        ...
296       city
297       brio
298       city
299       city
300       brio
Name: Car_Name, Length: 301, dtype: object

In [91]:
print(df.loc[0,"Car_Name"])

ritz

In [93]:
print(df.loc[[0,2]]) # getting data row wise

  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol
2     ciaz  2017           7.25           9.85        6900    Petrol

  Seller_Type Transmission  Owner
0      Dealer       Manual      0
2      Dealer       Manual      0

In [99]:
print(df.loc[df["Selling_Price"]>11.50])

          Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
50        fortuner  2012          14.90          30.61      104707    Diesel
51        fortuner  2015          23.00          30.61       40000    Diesel
52          innova  2017          18.00          19.77       15000    Diesel
53        fortuner  2013          16.00          30.61      135000    Diesel
59        fortuner  2014          19.99          35.96       41000    Diesel
62        fortuner  2014          18.75          35.96       78000    Diesel
63        fortuner  2015          23.50          35.96       47000    Diesel
64        fortuner  2017          33.00          36.23        6000    Diesel
66          innova  2017          19.75          23.15       11000    Petrol
69   corolla altis  2016          14.25          20.91       12000    Petrol
79        fortuner  2012          14.50          30.61       89000    Diesel
80   corolla altis  2016          14.73          14.89       23000    Diesel
82          innova  2017          23.00          25.39       15000    Diesel
83          innova  2015          12.50          13.46       38000    Diesel
86    land cruiser  2010          35.00          92.60       78000    Diesel
93        fortuner  2015          23.00          30.61       40000    Diesel
96          innova  2016          20.75          25.39       29000    Diesel
97   corolla altis  2017          17.00          18.64        8700    Petrol
211        elantra  2015          11.75          14.79       43535    Diesel
250          creta  2016          12.90          13.60       35934    Diesel

    Seller_Type Transmission  Owner
50       Dealer    Automatic      0
51       Dealer    Automatic      0
52       Dealer    Automatic      0
53   Individual    Automatic      0
59       Dealer    Automatic      0
62       Dealer    Automatic      0
63       Dealer    Automatic      0
64       Dealer    Automatic      0
66       Dealer    Automatic      0
69       Dealer       Manual      0
79       Dealer    Automatic      0
80       Dealer       Manual      0
82       Dealer    Automatic      0
83       Dealer       Manual      0
86       Dealer       Manual      0
93       Dealer    Automatic      0
96       Dealer    Automatic      0
97       Dealer       Manual      0
211      Dealer       Manual      0
250      Dealer       Manual      0

In [101]:
print(df.loc[df["Selling_Price"]>3.35],["Car_Name"])

          Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
1              sx4  2013           4.75           9.54       43000    Diesel
2             ciaz  2017           7.25           9.85        6900    Petrol
4            swift  2014           4.60           6.87       42450    Diesel
5    vitara brezza  2018           9.25           9.83        2071    Diesel
6             ciaz  2015           6.75           8.12       18796    Petrol
..             ...   ...            ...            ...         ...       ...
295           city  2015           8.55          13.09       60076    Diesel
296           city  2016           9.50          11.60       33988    Diesel
297           brio  2015           4.00           5.90       60000    Petrol
299           city  2017          11.50          12.50        9000    Diesel
300           brio  2016           5.30           5.90        5464    Petrol

    Seller_Type Transmission  Owner
1        Dealer       Manual      0
2        Dealer       Manual      0
4        Dealer       Manual      0
5        Dealer       Manual      0
6        Dealer       Manual      0
..          ...          ...    ...
295      Dealer       Manual      0
296      Dealer       Manual      0
297      Dealer       Manual      0
299      Dealer       Manual      0
300      Dealer       Manual      0

[156 rows x 9 columns] ['Car_Name']

In [102]:
print(df.iloc[1,2])

4.75

In [104]:
print(df.iloc[0:10,0:3])

        Car_Name  Year  Selling_Price
0           ritz  2014           3.35
1            sx4  2013           4.75
2           ciaz  2017           7.25
3        wagon r  2011           2.85
4          swift  2014           4.60
5  vitara brezza  2018           9.25
6           ciaz  2015           6.75
7        s cross  2015           6.50
8           ciaz  2016           8.75
9           ciaz  2015           7.45