In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("D:\Sumanth.xlsx")

In [4]:
df.head() # displaying first 5 rows of the dataframe

,StudentID,Name,Gender,Age,Departement,City,Marks,Attendance,Grade
0,101,Sumanth,Male,20,CSE,New York,85.0,95.0,b
1,102,Surendra,Male,21,MCE,London,75.0,37.0,C
2,103,Sunny,Male,22,DS,London,65.0,35.0,C
3,104,Bunny,Male,23,CSE,paris,30.0,44.0,F
4,105,sudheer,Male,24,MATHS,New York,84.0,55.0,C

In [6]:
df.tail() #displaying last 5 rows of the dataframe

,StudentID,Name,Gender,Age,Departement,City,Marks,Attendance,Grade
13,114,Lavanya,Female,33,DS,paris,69.0,64.0,C
14,115,Kavya,Female,34,MECL,New York,30.0,34.0,F
15,116,Surekha,Female,35,KDB,landon,38.0,54.0,F
16,117,Punith,Female,36,DJND,New York,NaN,NaN,NaN
17,118,Madhu babu,Male,37,NaN,New York,47.0,46.0,F

In [7]:
df.info() #displaying the information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    18 non-null     int64
 1   Name         18 non-null     object
 2   Gender       18 non-null     object
 3   Age          18 non-null     int64
 4   Departement  16 non-null     object
 5   City         18 non-null     object
 6   Marks        16 non-null     float64
 7   Attendance   16 non-null     float64
 8   Grade        16 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.4+ KB

In [8]:
df.describe() #displaying the statistical summary of the dataframe

       StudentID        Age        Marks  Attendance
count   18.000000  18.000000   16.000000    16.000000
mean   109.500000  28.500000   64.437500    45.625000
std      5.338539   5.338539   22.718476    18.571932
min    101.000000  20.000000   30.000000     5.000000
25%    105.250000  24.250000   46.250000    36.500000
50%    109.500000  28.500000   65.000000    45.000000
75%    113.750000  32.750000   84.250000    51.000000
max    118.000000  37.000000  100.000000    95.000000